// Generated by CoffeeScript 1.7.1
'use strict';

/*Controllers */
var controllers;

controllers = angular.module('myApp.controllers', []);

controllers.controller('MyCtrl1', [function() {}]);

controllers.controller('MyCtrl2', [function() {}]);
