// Generated by CoffeeScript 1.7.1
'use strict';

/*
Directives
 */
var directives;

directives = angular.module('myApp.directives', []);

directives.directive('appVersion', [
  'version', function(version) {
    return function(scope, elm, attrs) {
      elm.text(version);
    };
  }
]);
